yinglang_web:
  build: .
  command: bundle exec rails s -b 0.0.0.0 -p 3000
  container_name: yinglang-web-container
  volumes:
    # This seems to work as-is once you expose /Users to the boot2docker vm.
    - .:/rails_app
  ports:
    - "3000:3000"

  log_driver: "json-file"
  log_opt:
    max-size: "100k"
    max-file: "20"

  volumes_from:
    - bundle_yinglang

bundle_yinglang:
  # 'image' will vary depending on your docker-compose 
  # project name. You may need to run `docker-compose build web`
  # before this works.
  image: figrailsdev_yinglang_web
  command: echo "I'm a little data container, short and stout..."
  volumes:
    - /bundle
