mysql:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: fizzbuzz
  ports:
    - "3306:3306"
web:
  build: .
  command: bundle exec rails s -b 0.0.0.0 -p 3000
  container_name: nanyang-web-container
  volumes:
    # This seems to work as-is once you expose /Users to the boot2docker vm.
    - .:/rails_app
  links:
    - mysql
  ports:
    - "5000:3000"
