nanyang_mysql:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: fizzbuzz
  ports:
    - "3308:3306"
nanyang_web:
  build: .
  command: bundle exec rails s -b 0.0.0.0 -p 9000
  container_name: nanyang-web-container
  volumes:
    # This seems to work as-is once you expose /Users to the boot2docker vm.
    - .:/rails_app
  links:
    - nanyang_mysql
  ports:
    - "9000:9000"
