guodiantou-app-mysql:
  image: mysql:5.5.51
  environment:
    MYSQL_ROOT_PASSWORD: fizzbuzz
  ports:
    - "3308:3306"

guodiantou-app-server:
  build: .
  command: bundle exec rails s -b 0.0.0.0 -p 3000
  container_name: guodiantou-app-container
  volumes:
    # This seems to work as-is once you expose /Users to the boot2docker vm.
    - .:/rails_app
  links:
    - guodiantou-app-mysql

  # This tells the web container to mount the `bundle` images'
  # /bundle volume to the `web` containers /bundle path.
  volumes_from:
    - bundle

  ports:
    - "6000:3000"

# --- Add this to your fig.yml or docker-compose.yml file ---
bundle:
  # 'image' will vary depending on your docker-compose 
  # project name. You may need to run `docker-compose build web`
  # before this works.
  image: guodiantou-app-container
  command: echo I'm a little data container, short and stout...
  volumes:
    - /bundle
