version: '2'
services:
  guodiantou-app-mysql:
    container_name: maximo_mysql
    image: mysql:5.5.51
    environment:
      MYSQL_ROOT_PASSWORD: fizzbuzz
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  guodiantou-app-mysq2:
    image: mysql:5.5.51
    environment:
      MYSQL_ROOT_PASSWORD: fizzbuzz
    ports:
      - "3320:3306"

  guodiantou-app-server:
    build: .

    # command: bundle exec unicorn -c config/unicorn/production.rb
    # command: bundle exec rails s -b 0.0.0.0 -p 3000
    command: bundle exec puma -C config/unicorn/puma.rb
    volumes:
      # This seems to work as-is once you expose /Users to the boot2docker vm.
      - .:/rails_app
    depends_on:
      - guodiantou-app-mysql
    ports:
      - "5010:3000"
    volumes_from:
      - guodiantou-bundle

    extra_hosts:
      - "erptrn.cpihn.com:192.168.66.171"

  guodiantou-bundle:
    image: figrailsdev_guodiantou-app-server
    command: echo "I'm a little data container, short and stout..."
    volumes:
      - /bundle

volumes:
  mysql_data:
