version: '2'
services:
  njj_mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: fizzbuzz
    ports:
      - "3350:3306"

  njj_web:
    build: .
    command: bundle exec rails s -b 0.0.0.0 -p 3000
    container_name: njj-web-container
    volumes:
      # This seems to work as-is once you expose /Users to the boot2docker vm.
      - .:/rails_app
    depends_on:
      - njj_mysql
    ports:
      - "5010:3000"
    volumes_from:
      - njj_bundle

  njj_bundle:
    # 'image' will vary depending on your docker-compose 
    # project name. You may need to run `docker-compose build web`
    # before this works.
    image: figrailsdev_njj_web
    command: echo "I'm a little data container, short and stout..."
    volumes:
      - /bundle
