web:
  build: .
  command: bundle exec rails s -b 0.0.0.0 -p 3000
  volumes:
    # This seems to work as-is once you expose /Users to the boot2docker vm.
    - .:/rails_app
  ports:
    - "8080:8080"
    - "3000:3000"

  log_driver: "json-file"
  log_opt:
    max-size: "100k"
    max-file: "20"
