version: '2'
services:
  guodiantou-app-mysql:
    container_name: maximo_mysql
    image: mysql:5.5.51
    environment:
      MYSQL_ROOT_PASSWORD: fizzbuzz
    ports:
      - "3310:3306"

  guodiantou-app-server:
    build: .
    container_name: maximo_app_server
    #command: bundle exec unicorn
    command: bundle exec rails s -b 0.0.0.0 -p 3000
    volumes:
      # This seems to work as-is once you expose /Users to the boot2docker vm.
      - .:/rails_app
    links:
      - guodiantou-app-mysql
    ports:
      - "5000:3000"
    volumes_from:
      - guodiantou-bundle
    extra_hosts:
      - "erptrn.cpihn.com:192.168.66.171"

  guodiantou-bundle:
    container_name: maximo_bundler
    image: figrailsdev_guodiantou-app-server
    command: echo "I'm a little data container, short and stout..."
    volumes:
      - /bundle
